version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - erunion
  labels:
  - dependencies
- name: ReadMe API GitHub Sync
  uses: readmeio/github-readme-sync@2.0.0
